### ISSUE TITLE
Множество вещей

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#10]
/crawl
/lay 
и улучшить функцию садиться на игрока, чтобы игрок на которого сели мог нормально видеть

**Comment by rvbsm** [comment]
From README:

> `sit_on_players`: ___by default, when a player sits on a player, it blocks the field of view. To prevent this, install client-side mod__ (check additional files; bundled in full version)._

Just tell players to install the client or the full version of the mod.

![Modrinth](https://user-images.githubusercontent.com/39232658/234040832-c389d7cf-ea27-4eed-b63e-e0c10774597b.png)
![CurseForge](https://user-images.githubusercontent.com/39232658/234040877-a2b24d14-6bff-4d07-95bb-c15566f88d3e.png)

I haven't found any other solution, so this is the only way to fix it. Also, I don't know why Mojang doesn't allow you to ride the player even via the new `/ride` command 🤷‍♂️

> /crawl /lay

It's planned, but there is not much time for it yet. I'll leave this issue open

Thank you for your request

**Comment by wicivo** [comment]
Хорошо, спасибо

**Comment by wicivo** [comment]
Еще 1 идея. Чтобы игрок, на которого сели, мог скинуть игрока, например нажав 2 раза на шифт

**Comment by wicivo** [comment]
> Еще 1 идея. Чтобы игрок, на которого сели, мог скинуть игрока, например нажав 2 раза на шифт

Так же можно добавить черный список. Чтобы определенный игрок не мог на тебя сесть.

**Comment by wicivo** [comment]
Добавить возможность садиться на полублоки и ступеньки, нажав правой кнопкой мыши

**Comment by rvbsm** [comment]
Version [1.3.0](https://modrinth.com/mod/fsit/version/v1.3.0) added crawling, player dismounting, and ride blacklisting

**Comment by wicivo** [comment]
Спасибо большое!

**Comment by wicivo** [comment]
Фсит крашит на клиенте

**Comment by wicivo** [comment]
На сервере по ещё не проверял

**Comment by wicivo** [comment]
https://mclo.gs/BjedPbt

**Comment by wicivo** [comment]
Кажется из-за modmenu, сейчас проверю

**Comment by wicivo** [comment]
А точнее от его отсутствия

**Comment by wicivo** [comment]
Да, если ModMenu не установлен, то Fsit крашит игру

**Comment by rvbsm** [comment]
> Кажется из-за modmenu, сейчас проверю

Yep, fixed in da6f0ac. I think that's not such a big problem, so I'll publish it with the next minor update.

P.S. It would be better to create a new issue rather than posting unrelated info here. I'm not closing this issue 'cause of the laying feature. Thanks for understanding

**Comment by wicivo** [comment]
ок

**Comment by rvbsm** [comment]
Closing the issue. It has been partially completed and partially moved to the #33
