### ISSUE TITLE
Невидно когда не тебе сидит игрока

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#13]
![2023-05-02_12 45 40](https://user-images.githubusercontent.com/116191734/235609039-85d84f08-7cdf-47fb-853e-13a5d487caa4.png)
![2023-05-02_12 45 35](https://user-images.githubusercontent.com/116191734/235609068-6003606e-e0ad-4ed2-9ec1-6bdb099486c0.png)
![2023-05-02_12 48 46](https://user-images.githubusercontent.com/116191734/235609428-25f50e89-d55a-425a-bbae-06a0424b66b9.png)

**Comment by rvbsm** [comment]
Can't reproduce. Conflict with other mod?

![image](https://user-images.githubusercontent.com/39232658/235628272-1b6e705f-df4a-4798-be41-dca7ba6bcf94.png)
![image](https://user-images.githubusercontent.com/39232658/235628441-b06425c2-b1fb-41c8-a546-858c0b857667.png)

**Comment by wicivo** [comment]
Хм, может я не совсем понял как он работает

**Comment by wicivo** [comment]
Чтобы я видел, у игрока, который сидит на мне должен быть установлен мод?

**Comment by rvbsm** [comment]
> Чтобы я видел, у игрока, который сидит на мне должен быть установлен мод?

No, the client part of the mod only works on the client.

I have tested several times with different combinations and everything works. Maybe some mod conflicts? Provide a list of installed mods, I'll try to check with them

**Comment by wicivo** [comment]
Секунду

**Comment by wicivo** [comment]
![image](https://user-images.githubusercontent.com/116191734/235989229-c721c759-cfd4-4fd3-9fd5-8838e7429179.png)

**Comment by wicivo** [comment]
I use my own optimization modpack, which is stacked on Modrinth, as well as a couple of client mods that make my game a little more convenient and enjoyable

**Comment by wicivo** [comment]
Опять перевел на английский по привычке :) Последнее время много общаюсь с англичанами.

**Comment by rvbsm** [comment]
Can you please check if it works? Only client-side

[artifact.zip](https://github.com/rvbsm/fsit/suites/12656157163/artifacts/678266502)

**Comment by wicivo** [comment]
ок

**Comment by wicivo** [comment]
Вроде работает

**Comment by rvbsm** [comment]
Ok, thank's! I'm releasing it

**Comment by wicivo** [comment]
@rvbsm Здравствуйте, на версии 1.20.2 вроде все видно и без мода на клиенте

**Comment by rvbsm** [comment]
> @rvbsm Здравствуйте, на версии 1.20.2 вроде все видно и без мода на клиенте

Yes, I am currently updating the mod to 1.20.2, and it is true. Mojang removed the stupid height offset, but the hitbox of the player riding you blocks the interaction itself. So maybe the client-side will only be needed to sync the config and block some annoying players.

Thanks for the additional info!
