### ISSUE TITLE
Config in-game

### ISSUE THREAD

**Issue by bernzrdo** [rvbsm/fsit#17]
**Is your feature request related to a problem? Please describe.**
Searching for the config file and editing with notepad is frustrating and boring.

**Describe the solution you'd like**
Add a config UI acessible by [Mod Menu](https://modrinth.com/mod/modmenu).

**Comment by rvbsm** [comment]
Did you mean changing config for singleplayer or for player at server?

**Comment by bernzrdo** [comment]
For singleplayer. I know this is a mod for servers, but I use it on singleplayer and LAN worlds that I host.

**Comment by rvbsm** [comment]
There is already config menu in mod. Maybe you should to download Cloth Config API mod

**Comment by bernzrdo** [comment]
Oops, sorry!

When I hover the mod, doesn't show the usual settings icon, so I thought it didn't have config UI.
![image](https://github.com/rvbsm/fsit/assets/27358071/ece5ddba-6187-44ec-bc73-0da80cc58a8e)
