### ISSUE TITLE
Конфигурация радиуса

### ISSUE THREAD

**Issue by Rozbiynk** [rvbsm/fsit#18]
**Is your feature request related to a problem? Please describe.**
Слишком большой радиус, при котором можно сесть на игрока. Из за этого некоторые действия трудно выполнять

**Describe the solution you'd like**
Добавить в конфиг возможность менять радиус

**Comment by rvbsm** [comment]
Done in [v1.3.0](https://modrinth.com/mod/fsit/version/v1.3.0)
