### ISSUE TITLE
height

### ISSUE THREAD

**Issue by arkksu** [rvbsm/fsit#19]
height from the head of the player while riding in config

**Comment by rvbsm** [comment]
Hi, for what purposes exactly it is needed?

**Comment by arkksu** [comment]
Because players  are literally sitting on their heads, I would like there to be a space between the player's head and the other's back

upd: don't resolved, first issue on github :)

**Comment by rvbsm** [comment]
Just want to assure that the default behavior is this:
![image](https://github.com/rvbsm/fsit/assets/39232658/5b4799ae-27eb-464e-988e-999a0c0b8c0e)
![image](https://github.com/rvbsm/fsit/assets/39232658/f941e176-5979-489c-9774-3c0f5c3b04e1)

But okay, I'll try to do something.

> upd: don't resolved, first issue on github :)

Congrats :)

**Comment by rvbsm** [comment]
Added in [v1.3.1](https://modrinth.com/mod/fsit/version/v1.3.1).
