### ISSUE TITLE
Player stops crawling if block above is non-full

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#20]
https://youtu.be/vhgm85BX5b8

**Comment by wicivo** [comment]
Ой, изначально видео было не доступно, но я исправил это

**Comment by rvbsm** [comment]
Yeah, that's how implemented to prevent players from standing up. With mod installed on client, there is no support block/shulker for crawling.

I don't like the implementation either, but after checking the GSit source code I saw that they do it pretty much the same way, so I left it as is.

So there is only a bug when crawling in non-full vertical blocks? (glass panes, fences, walls etc.)

**Comment by wicivo** [comment]
Про заборы и ограды я не знаю

**Comment by wicivo** [comment]
https://youtu.be/67jhEwM6DfI

**Comment by rvbsm** [comment]
> [youtu.be/67jhEwM6DfI](https://youtu.be/67jhEwM6DfI)

Thanks for feedback. I'm trying to make it work now.

**Comment by rvbsm** [comment]
Fixed in [v1.3.1](https://modrinth.com/mod/fsit/version/v1.3.1).
