### ISSUE TITLE
1.3.1 не позволяет запустить майнкрафт

### ISSUE THREAD

**Issue by Rozbiynk** [rvbsm/fsit#21]
**Describe the bug**
При попытки запуска игры лаунчер выдает exception

**To Reproduce**
Установить fsit 1.3.1
Запустить майнкрафт через prism launcher

**Expected behavior**
Запускаться

**Screenshots**
![изображение](https://github.com/rvbsm/fsit/assets/95433246/54a52256-db93-49a2-9676-3e5de5805258)

**Logs**
https://mclo.gs/3hEBVa4

**Info (please complete the following information):**
 - OS: Win 11
 - Minecraft Version: 1.20.1
 - Mod Version: 1.3.1

**Comment by rvbsm** [comment]
Yep, that's the release problem. I'm re-uploaded mod to [Modrinth](https://modrinth.com/mod/fsit/version/v1.3.1) and wait for approving from CurseForge. Sorry for the inconvenience.

**Comment by Rozbiynk** [comment]
still have same issue
![изображение](https://github.com/rvbsm/fsit/assets/95433246/85657587-acc3-41b2-8c79-c32083802b14)

**Comment by rvbsm** [comment]
Are you re-downloaded FSit? If there is __fsit-1.3.1-shadow.jar__ you need to remove it and replace with [__fsit-1.3.1.jar__](https://cdn.modrinth.com/data/J5NAzRqK/versions/4rjppqSG/fsit-v1.3.1.jar).

**Comment by rvbsm** [comment]
I've republished a release, because Modrinth didn't actually replace a jar file on servers. Now it's launching without problems (want to believe).
