### ISSUE TITLE
Configuration File Issue

### ISSUE THREAD

**Issue by C0D6WasTaken** [rvbsm/fsit#22]
**Describe the bug**
The configuration file resets after each server shutdown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a 1.20+ quilt server with the mod.
2. Change any boolean to a different value and save.
3. Reset the server and reopen the configuration file.

**Expected behaviour**
The configuration file applies the changes made and modifies the mod's functionality.

**Logs**
Or crash-report.

**Info (please complete the following information):**
-  Minecraft v1.20+
-  latest Quilt Server & QFAPI
-  v1.3.1 of the mod

**Additional context**
The mod cannot be reloaded directly from the server after applying the changes to the configuration file. There is no information written inside the log file regarding the mod.

**Comment by rvbsm** [comment]
Fixed in [v1.3.2](https://modrinth.com/mod/fsit/version/v1.3.2)
