### ISSUE TITLE
/crawl не работает

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#23]
Как только пишешь команду, он тебя немного прогибает, но ты тут же встаешь.

**Comment by rvbsm** [comment]
~~Provide a list of installed mods, please.~~

An issue is that pose isn't synced with client

**Comment by rvbsm** [comment]
Fixed in [v1.4.1](https://modrinth.com/mod/fsit/version/v1.4.1)

**Comment by wicivo** [comment]
Ok
