### ISSUE TITLE
Нельзя скинуть игрока, если он на тебя сел

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#24]
Вроде этот баг появился с версии 1.20.2

**Comment by rvbsm** [comment]
In order to dismount a player off you, you need to look up and double sneak, or block them using the Social Interaction Screen. If that didn't work, send me a copy of the configuration, please.

**Comment by wicivo** [comment]
> In order to dismount a player off you, you need to look up and double sneak, or block them using the Social Interaction Screen. If that didn't work, send me a copy of the configuration, please.

config_version = 4

[sneak]
enabled = false
angle = 66.0
delay = 600

[sittable]
enabled = true
radius = 2
blocks = []
tags = []

[riding]
enabled = true
radius = 3

[commands]
enabled = true
sit = "sit"
crawl = "crawl"

**Comment by rvbsm** [comment]
Released [v1.4.2](https://modrinth.com/mod/fsit/version/v1.4.2) :skull: 

Btw, thank you for your contributions!
