### ISSUE TITLE
Trying to ride self in freecam causes server crash!

### ISSUE THREAD

**Issue by thexavier666** [rvbsm/fsit#25]
**Describe the bug**
I'm using freecam (modrinth edition) and when I'm in freecam mode (not spectator since my original body is still where it is) I accidentally tried to ride myself. This caused the server to crash. I have tried this with other players on the server as well. 

**To Reproduce**
1. Install freecam and fsit
2. Press F4 (default) to detach camera from player
3. Move and right click (or which ever key is for sit) on your self
4. Make sure player sitting is enabled in the config file

**Expected behavior**
Ideally, nothing should happen since a player should not be able to ride themselves

**Screenshots**

**Logs**
I need to crash my server again to do it. If it's really important, I'll do it :(

**Info (please complete the following information):**
 - OS: Linux ARM64 Ubuntu 22.04
 - Minecraft Version: 1.20.1
 - Mod Version: 1.3.2

**Additional context**
If I use the carpet player use command, I think the issue doesn't happen AFAIK (not fully tested though). Happens for sure if I right click on myself in freecam mode.
Remember, this only happens in freecam, not in normal vanilla gameplay.

**Comment by rvbsm** [comment]
Thank you for contributing!

I can't test it right now, so a patch release will be delayed. If you need it ASAP, you can use [the developer version with hotfix](https://github.com/rvbsm/fsit/suites/18100415153/artifacts/1043227751). **fsit-5c4a283.jar** is what you need from this archive

**Comment by rvbsm** [comment]
Fixed in v1.5.0.

[1.20-1.20.1](https://modrinth.com/mod/fsit/version/v1.5.0-1.20) and [1.20.2](https://modrinth.com/mod/fsit/version/v1.5.0-1.20.2)
