### ISSUE TITLE
FSit gives mismatch error on server

### ISSUE THREAD

**Issue by Kichura** [rvbsm/fsit#27]
**Describe the bug**
When connecting to the server with a vanilla client, the connection passes properly - However connecting with a fabric client with fabric api installed causes server to tell to client that FSit has a mismatch from both sides.

**To Reproduce**
1. Install the FSit mod to the server,
2. Install Fabric API to the same server,
3. Run server,
4. Try to join with both vanilla and fabric clients respectively,
5. Notice fabric client cannot connect.

**Expected behavior**
Both clients can connect properly without any issues.

**Screenshots**
![a](https://github.com/rvbsm/fsit/assets/68134602/e6cd62f7-f98c-46d4-b5f3-ac45c9fe870f)

**Logs**
*(Crash report is not available)*

**Info (please complete the following information):**
 - OS: Fedora Linux
 - Minecraft Version: 1.20.2
 - Mod Version: v1.5.0-1.20.2

**Additional context**
I may suspect that fsit is supposed to ask the client to have the mod installed on it too *(which didn't work)* or mod wasn't properly designed to be fully vanilla-friendly for both clients.

**Comment by rvbsm** [comment]
Oops, sorry about that. I didn't test this case before the release, but I think the problem comes from `fabric-registry-sync` and that I registered a new argument type for command autocompletion.

I'll try to fix it tomorrow, thanks for contributing

**Comment by venaminecraft** [comment]
Thanks 😊

**Comment by rvbsm** [comment]
Fixed in v1.5.1 — [1.20](https://modrinth.com/mod/fsit/version/v1.5.1-1.20) and [1.20.2](https://modrinth.com/mod/fsit/version/v1.5.1-1.20.2)

Sorry again for not properly testing before the release
