### ISSUE TITLE
bug: Commands don't work

### ISSUE THREAD

**Issue by megatrook** [rvbsm/fsit#32]
### 🔍 What happened?

I tried to use /sit or /fsit like the mod's page describes, but those commands don't seem to be recognized at all.
![image](https://github.com/rvbsm/fsit/assets/77197776/46131da4-aeed-4d89-8343-9c82be1c6596)

### 🤔 What did you expect to happen?

I expected the commands to work like described on the mod's page. /sit would presumably allow me to sit, and /fsit would allow me to configure the mod to some extent

### 📦 Version

1.5.1

### ⛏ Minecraft Version

1.20.1

**Comment by rvbsm** [comment]
Commands are registered only when the mod is running on the server. But if there is a demand, I'll add them for the client as well

**Comment by megatrook** [comment]
i think it'd be nice! if it isn't too much of a hassle. could be cool for LAN worlds and such, and i also personally would prefer it over pressing shift twice while looking down

**Comment by rvbsm** [comment]
Commands were added to the client too, but you can use the keybindings. Thank you for the idea!
