### ISSUE TITLE
feat: disable right click to sit

### ISSUE THREAD

**Issue by AllOutJay** [rvbsm/fsit#37]
### ✍️ Describe the feature you'd like to request

I would like there to be an option to disable right click to sit and instead use the /sit command. I think right clicking to sit is prone to lots of accidental sittings while build or even just playing. So to help avoid that, I think it would be great to encourage the use of commands or even double sneaking.

### 💡 Describe the solution you'd like to see

A configuration option for right click to sit. It would then force the user to use /sit or double sneak if applicable.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by rvbsm** [comment]
There is already `on_use.sitting` option in config that handles this, if I understood you correctly

**Comment by AllOutJay** [comment]
You would be right! I misunderstood that config option as preventing me from sitting all together and not just right clicks. Appreciate the quick clarification.

**Comment by rvbsm** [comment]
> I think right clicking to sit is prone to lots of accidental sittings while build or even just playing.

I completely agree with this. Starting with v2.1.0, I made it so that you can start sitting only when items in both hands are not going to be used. Thus, you can sit, for instance, with a totem in your offhand, but not with blocks.

**Comment by rvbsm** [comment]
> You would be right! I misunderstood that config option as preventing me from sitting all together and not just right clicks. Appreciate the quick clarification.

That's okay. Thanks anyway, I may need to document it better
