### ISSUE TITLE
bug: Leaving while riding a player teleports them to limbo

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [rvbsm/fsit#42]
### 🔍 What happened?

Leaving the server while riding someone teleports them to limbo where they can place blocks, but cant break, cant see entities and ETC

### 🤔 What did you expect to happen?

Not teleporting player to limbo

### 📦 Version

fsit-2.5.2+1.21

### ⛏ Minecraft Version

1.21.1

**Comment by rvbsm** [comment]
Typo, thank you for opening the issue, will be fixed in the next release
