### ISSUE TITLE
bug: Incompatible with Fabric Language Kotlin 1.12.2+kotlin.2.0.20

### ISSUE THREAD

**Issue by TheWhiteDog9487** [rvbsm/fsit#43]
### 🔍 What happened?

The game crashes immediately after launch
The problem disappears after changing Fabric Language Kotlin to version fabric-language-kotlin-1.12.1+kotlin.2.0.20

How to reproduce:
1. Install Minecraft 1.21
2. Install Fabric Loader 0.16.5
3. Install mods:
    1. fabric-api-0.102.0+1.21.jar
    2. fabric-language-kotlin-1.12.2+kotlin.2.0.20.jar
    3. fsit-2.5.2+1.21.jar
4. Launch the game

[minecraft-exported-crash-info-2024-09-21T06-40-19.zip](https://github.com/user-attachments/files/17081455/minecraft-exported-crash-info-2024-09-21T06-40-19.zip)

### 🤔 What did you expect to happen?

Normal launch

### 📦 Version

fsit-2.5.2+1.21

### ⛏ Minecraft Version

Minecraft 1.21 + Fabric Loader 0.16.5

**Comment by rvbsm** [comment]
Kotlin moment, thank you for reporting, will be fixed in the next release

**Comment by OoLunar** [comment]
Could we get a new release soon please? I would like to add this mod to my 1.21 server :eyes:
