### ISSUE TITLE
feat: A configuration option to center where player's sit

### ISSUE THREAD

**Issue by OoLunar** [rvbsm/fsit#44]
### ✍️ Describe the feature you'd like to request

When a player sits down on a block, they're placed exactly where they're looking. This is great for roleplay or when you have advanced chairs, but when you have OCD it's really bothersome.

### 💡 Describe the solution you'd like to see

A configuration option - either local or global - to allow for the player to be automatically centered to the block/slab.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by rvbsm** [comment]
Alright, sounds like a good idea

**Comment by rvbsm** [comment]
The feature is out in v2.6.0-beta.2

**Comment by OoLunar** [comment]
Works like a charm!
