### ISSUE TITLE
bug: Crash due to lack of "fsit.yml" config file

### ISSUE THREAD

**Issue by Vi-Tul** [rvbsm/fsit#46]
### 🔍 What happened?

When this mod is first launched, it tries to find the "fsit.yml" file in config folder, but it is not there, which is why the game crashes. Creating empty "fsit.yml" file solves the issue
Unfortunately, the exact error message and logs are lost

### 🤔 What did you expect to happen?

Game launching

### 📦 Version

2.6.0-beta.2

### ⛏ Minecraft Version

1.21

**Comment by rvbsm** [comment]
Oopsie, forgor to check if a file exists. Thanks for pointing that out

**Comment by rvbsm** [comment]
As this issue is related only to the beta branch, closing as released in v2.6.0-beta.3
