### ISSUE TITLE
It's not really a Feature request.

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#5]
I have a question. Is there any way to disable sit when you press the shift

**Comment by wicivo** [comment]
my players ask me to turn it off

**Comment by rvbsm** [comment]
There is currently no disable option, but `min_angle` can be set to 90 in the config file. It won't turn off completely, but Shift will only work when you look straight down. Later I'll add the ability to disable it completely

**Comment by wicivo** [comment]
Okay, thank you!

**Comment by NerdTo** [comment]
Руслан ты русский? @rvbsm

**Comment by NerdTo** [comment]
Или украинец?

**Comment by wicivo** [comment]
🥲

**Comment by wicivo** [comment]
Can I speak to you in Russian?

**Comment by rvbsm** [comment]
Sorry, I didn't see that you are the author of the issue. I'm Ukrainian, if that means anything. 

> Can I speak to you in Russian?

Yeah, I'm understand Russian, but prefer English

**Comment by wicivo** [comment]
На самом деле не имеет значения русский ты или украинец, это имелось ввиду как - можно ли с тобой разговаривать в дальнейшем на русском для удобства. Ну я уже увидел, что можно. Хорошо
