### ISSUE TITLE
Элитры

### ISSUE THREAD

**Issue by wicivo** [rvbsm/fsit#9]
Не знаю  вызвано ли это Fsit, но у меня есть это https://youtu.be/Pcx1zh6xPjY

**Comment by rvbsm** [comment]
It looks like a bug related to the change of dimension from End to Overworld. Did you fly to the End Portal with Elytras?

**Comment by wicivo** [comment]
Нет

**Comment by rvbsm** [comment]
Ok, then please add some context to how it happened so I can either reproduce or at least follow how it happens

**Comment by wicivo** [comment]
На самом деле это происходит рандомно

**Comment by wicivo** [comment]
В 1 одну из нескольких попыток это может произойти, я пока не выявил явной причины

**Comment by wicivo** [comment]
Я могу отправить мод лист

**Comment by wicivo** [comment]
![image](https://user-images.githubusercontent.com/116191734/233838497-155ec8e3-20a2-4b68-ac38-2ae0bce23135.png)

**Comment by rvbsm** [comment]
Thanks! Can you describe the approximate way in which this bug occurs?

**Comment by wicivo** [comment]
Взлететь, приземлиться. Готово!)

**Comment by wicivo** [comment]
Это исправляется перезаходом на сервер

**Comment by wicivo** [comment]
Несколько моих игроков жаловались на эту проблему, и она так же была у меня несколько раз, так что теорию о том, что это только у этого игрока можно отложить

**Comment by wicivo** [comment]
Так же если просто снять элитры во время этой ошибки, то она не пропадет

**Comment by wicivo** [comment]
Еще могу сказать, что для воспроизведения ошибки не обязательны феерверки

**Comment by wicivo** [comment]
https://youtu.be/3MSno8y7wFI

**Comment by wicivo** [comment]
У меня получилось заснять это

**Comment by wicivo** [comment]
Okay, I'll try to delete Fsit and try to do it again

**Comment by wicivo** [comment]
> Okay, I'll try to delete Fsit and try to do it again

По привычке перевел с помощью переводчика :)

**Comment by wicivo** [comment]
Эта ошибка не из-за Fsit

**Comment by wicivo** [comment]
👍

**Comment by rvbsm** [comment]
> Эта ошибка не из-за Fsit

I think you need to look at Emotecraft, idk. Good luck
